version: '3.3'

services:
  vnf1:
    image: augugrumi/addervnf:latest
    expose:
      - "55631"
    restart: always
    ports:
      - "55631:55631"
    environment:
      PORT: 55631
      STRING_TO_ADD: vnf1

  vnf2:
    image: augugrumi/addervnf:latest
    expose:
      - "55632"
    restart: always
    ports:
      - "55632:55632"
    environment:
      PORT: 55632
      STRING_TO_ADD: vnf2

  launcher:
    image: augugrumi/launchervnf:latest
    restart: always
    ports:
      - "55633:80"
    environment:
      PORT: 55633
      LINKS: http://vnf1:55631 http://vnf2:55632 http://192.168.1.2:55634
